sudo: required
services:
  - docker

before install:

- docker build -t clivefon/react-test -f ./client/Dockerfile.dev ./client

script:
- docker run clivefon/react-test npm test -- --coverage

after success:
- docker build -t clivefon/multi-client ./client
- docker build -t clivefon/multi-nginx ./nginx
- docker build -t clivefon/multi-server ./server
- docker build -t clivefon/mutti-worker ./worker

# Log into docker CLI 
  echo "$Docker_password" | docker login -u "$Docker_ID" --password-stdin
# Take all those images and push to docker hup
- docker push clivefon/multi-client
- docker push clivefon/multi-nginx
- docker push clivefon/multi-server
- docker push clivefon/multi-worker





